//FETCH_DATA_MENU_REQUEST
export const FETCH_DATA_MENU_REQUEST = 'FETCH_DATA_MENU_REQUEST';
//FETCH DATA MOVIE LIST REQUEST
export const FETCH_DATA_MOVIELIST_REQUEST = "FETCH_DATA_MOVIELIST_REQUEST";
//FETCH_DATA_VIDEODETAIL_REQUEST
export const FETCH_DATA_VIDEODETAIL_REQUEST = "FETCH_DATA_VIDEODETAIL_REQUEST";
//FETCH DATA RELATEDVIDEOS REQUEST
export const FETCH_DATA_RELATEDVIDEOS_REQUEST = "FETCH_DATA_RELATEDVIDEOS_REQUEST";
//FETCH_DATA_ALLVIDEOS_REQUEST
export const FETCH_DATA_ALLVIDEOS_REQUEST = "FETCH_DATA_ALLVIDEOS_REQUEST";